export const mapping: Record<string, string> = {
  "напрајДаЕ": "map",
  "наследуе од": "extends",
  "наследуе": "extends",
  "функција": "function",
  "Запис": "Record",
  "тури": "push",
  "главна": "default",
  "главно": "default",
  "ај": "let",
  "фиксно": "const",
  "нурај": "require",
  "унеси": "import",
  "избаци": "export",
  "нешто": "let",
  "некој": "let",
  "да е": "=",
  "нека е": "=",
  "нека биде": "=",
  "ако": "if",
  "\\sу\\s": " of ",
  "пиши": "console.log",
  "нов": "new",
  "дај му": "return",
  "врати": "return",
  "напрај нова": "new",
  "напрај нов": "new",
  "класа": "class",
  "текст": "string",
  "бројче": "number",
  "бе даа": "",
  "даа": "",
  "даe": "",
  "јавно": "public",
  "типот": "type",
  "\\bвоа\\b": "this",
  "\\bја\\b": "this",
  "мое": "private",
  "наше": "protected",
  "конструктор": "constructor",
  "\\bод\\b": "extends",
  "\\sинаку\\s": "else",
  "\\bи\\b": "&&",
  "\\bили\\b": "||",
  "\\sе поголемо од\\s": ">",
  "\\sе помало од\\s": "<",
  "\\bза\\b": "for",
  "\\sза\\s": "for"
}